(block
  (fun rh_hash_i64 ((var key i64)) -> i64
    (block
      (var h = (cast key u64))
      (= h (xor h (>> h (: 12 u64))))
      (= h (xor h (<< h (: 25 u64))))
      (= h (xor h (>> h (: 27 u64))))
      (= h (* h (: 2685821657736338717 u64)))
      (return (cast h i64))))

  ;; Standalone prototypes of reducers that will later be injected from the
  ;; Aggregation node into the generated AST.
  (fun agg_count_step ((var prev i64) (var value i64) (var is_new bool)) -> i64
    (block
      (return (+ prev (: 1 i64)))))

  (fun agg_sum_i64_step ((var prev i64) (var value i64) (var is_new bool)) -> i64
    (block
      (return (+ prev value))))

  (fun count_lookup ((var ht <ref HashTable>) (var key i64)) -> i64
    (block
      (var capacity = (field ht Capacity))
      (if (<= capacity (: 0 i64)) (block (return (: -1 i64))))
      (var keys = (field ht Keys))
      (var dist = (field ht Dist))
      (var slot_ids = (field ht SlotId))
      (var slot = (& (call rh_hash_i64 key) (- capacity (: 1 i64))))
      (var probe_dist i64)
      (= probe_dist (: 0 i64))
      (while (< probe_dist capacity)
        (block
          (var resident_dist = (index dist slot))
          (if (|| (== resident_dist (: -1 i64)) (< resident_dist probe_dist))
            (block (return (: -1 i64))))
          (if (== (index keys slot) key)
            (block (return (index slot_ids slot))))
          (= slot (& (+ slot (: 1 i64)) (- capacity (: 1 i64))))
          (= probe_dist (+ probe_dist (: 1 i64)))))
      (return (: -1 i64))))

  (fun count_insert_existing ((var keys <ptr i64>)
                              (var dist <ptr i64>)
                              (var slot_ids <ptr i64>)
                              (var capacity i64)
                              (var key i64)
                              (var dense_slot i64)) -> bool
    (block
      (var carried_key = key)
      (var carried_dist i64)
      (= carried_dist (: 0 i64))
      (var carried_slot = dense_slot)
      (var slot = (& (call rh_hash_i64 key) (- capacity (: 1 i64))))
      (var probes i64)
      (= probes (: 0 i64))
      (while (< probes capacity)
        (block
          (var resident_dist = (index dist slot))
          (if (== resident_dist (: -1 i64))
            (block
              (= keys [slot] carried_key)
              (= dist [slot] carried_dist)
              (= slot_ids [slot] carried_slot)
              (return #t)))
          (if (< resident_dist carried_dist)
            (block
              (var resident_key = (index keys slot))
              (var resident_slot = (index slot_ids slot))
              (= keys [slot] carried_key)
              (= dist [slot] carried_dist)
              (= slot_ids [slot] carried_slot)
              (= carried_key resident_key)
              (= carried_dist resident_dist)
              (= carried_slot resident_slot)))
          (= slot (& (+ slot (: 1 i64)) (- capacity (: 1 i64))))
          (= carried_dist (+ carried_dist (: 1 i64)))
          (= probes (+ probes (: 1 i64)))))
      (return #f)))

  (fun count_init ((var ht <ref HashTable>) (var capacity i64)) -> bool
    (block
      (if (|| (< capacity (: 1 i64))
              (> capacity (: 1152921504606846975 i64)))
        (block (return #f)))
      (var bytes = (* capacity (: 8 i64)))
      (var keys = (cast (call qdb_alloc bytes) <ptr i64>))
      (var dist = (cast (call qdb_alloc bytes) <ptr i64>))
      (var slot_ids = (cast (call qdb_alloc bytes) <ptr i64>))
      (var group_keys = (cast (call qdb_alloc bytes) <ptr i64>))
      (var counts = (cast (call qdb_alloc bytes) <ptr i64>))
      (var sums = (cast (call qdb_alloc bytes) <ptr i64>))
      (var agg_buffers = (cast (call qdb_alloc (: 16 i64)) <ptr <ptr i64>>))
      (if (|| (== (cast keys i64) (: 0 i64))
              (|| (== (cast dist i64) (: 0 i64))
                  (|| (== (cast slot_ids i64) (: 0 i64))
                      (|| (== (cast group_keys i64) (: 0 i64))
                          (|| (== (cast counts i64) (: 0 i64))
                              (|| (== (cast sums i64) (: 0 i64))
                                  (== (cast agg_buffers i64) (: 0 i64))))))))
        (block
          (if (!= (cast keys i64) (: 0 i64)) (block (call qdb_free (cast keys <ptr i8>))))
          (if (!= (cast dist i64) (: 0 i64)) (block (call qdb_free (cast dist <ptr i8>))))
          (if (!= (cast slot_ids i64) (: 0 i64)) (block (call qdb_free (cast slot_ids <ptr i8>))))
          (if (!= (cast group_keys i64) (: 0 i64)) (block (call qdb_free (cast group_keys <ptr i8>))))
          (if (!= (cast counts i64) (: 0 i64)) (block (call qdb_free (cast counts <ptr i8>))))
          (if (!= (cast sums i64) (: 0 i64)) (block (call qdb_free (cast sums <ptr i8>))))
          (if (!= (cast agg_buffers i64) (: 0 i64)) (block (call qdb_free (cast agg_buffers <ptr i8>))))
          (return #f)))
      (var i i64)
      (= i (: 0 i64))
      (while (< i capacity)
        (block
          (= keys [i] (: 0 i64))
          (= dist [i] (: -1 i64))
          (= slot_ids [i] (: -1 i64))
          (= group_keys [i] (: 0 i64))
          (= counts [i] (: 0 i64))
          (= sums [i] (: 0 i64))
          (= i (+ i (: 1 i64)))))
      (= agg_buffers [(: 0 i64)] counts)
      (= agg_buffers [(: 1 i64)] sums)
      (field_assign ht Keys keys)
      (field_assign ht Dist dist)
      (field_assign ht SlotId slot_ids)
      (field_assign ht GroupKeys group_keys)
      (field_assign ht AggBuffers agg_buffers)
      (field_assign ht Capacity capacity)
      (field_assign ht Size (: 0 i64))
      (field_assign ht NumAggs (: 2 i64))
      (field_assign ht NumKeys (: 1 i64))
      (return #t)))

  (fun count_destroy ((var ht <ref HashTable>))
    (block
      (var agg_buffers = (field ht AggBuffers))
      (if (!= (cast agg_buffers i64) (: 0 i64))
        (block
          (var counts = (index agg_buffers (: 0 i64)))
          (var sums = (index agg_buffers (: 1 i64)))
          (if (!= (cast counts i64) (: 0 i64))
            (block (call qdb_free (cast counts <ptr i8>))))
          (if (!= (cast sums i64) (: 0 i64))
            (block (call qdb_free (cast sums <ptr i8>))))
          (call qdb_free (cast agg_buffers <ptr i8>))))
      (if (!= (cast (field ht Keys) i64) (: 0 i64)) (block (call qdb_free (cast (field ht Keys) <ptr i8>))))
      (if (!= (cast (field ht Dist) i64) (: 0 i64)) (block (call qdb_free (cast (field ht Dist) <ptr i8>))))
      (if (!= (cast (field ht SlotId) i64) (: 0 i64)) (block (call qdb_free (cast (field ht SlotId) <ptr i8>))))
      (if (!= (cast (field ht GroupKeys) i64) (: 0 i64)) (block (call qdb_free (cast (field ht GroupKeys) <ptr i8>))))
      (field_assign ht Keys (cast (: 0 i64) <ptr i64>))
      (field_assign ht Dist (cast (: 0 i64) <ptr i64>))
      (field_assign ht SlotId (cast (: 0 i64) <ptr i64>))
      (field_assign ht GroupKeys (cast (: 0 i64) <ptr i64>))
      (field_assign ht AggBuffers (cast (: 0 i64) <ptr <ptr i64>>))
      (field_assign ht Capacity (: 0 i64))
      (field_assign ht Size (: 0 i64))
      (field_assign ht NumAggs (: 0 i64))))

  (fun count_rehash ((var ht <ref HashTable>) (var new_capacity i64)) -> bool
    (block
      (if (|| (< new_capacity (: 1 i64))
              (> new_capacity (: 1152921504606846975 i64)))
        (block (return #f)))
      (var bytes = (* new_capacity (: 8 i64)))
      (var new_keys = (cast (call qdb_alloc bytes) <ptr i64>))
      (var new_dist = (cast (call qdb_alloc bytes) <ptr i64>))
      (var new_slot_ids = (cast (call qdb_alloc bytes) <ptr i64>))
      (var new_group_keys = (cast (call qdb_alloc bytes) <ptr i64>))
      (var new_counts = (cast (call qdb_alloc bytes) <ptr i64>))
      (var new_sums = (cast (call qdb_alloc bytes) <ptr i64>))
      (if (|| (== (cast new_keys i64) (: 0 i64))
              (|| (== (cast new_dist i64) (: 0 i64))
                  (|| (== (cast new_slot_ids i64) (: 0 i64))
                      (|| (== (cast new_group_keys i64) (: 0 i64))
                          (|| (== (cast new_counts i64) (: 0 i64))
                              (== (cast new_sums i64) (: 0 i64)))))))
        (block
          (if (!= (cast new_keys i64) (: 0 i64)) (block (call qdb_free (cast new_keys <ptr i8>))))
          (if (!= (cast new_dist i64) (: 0 i64)) (block (call qdb_free (cast new_dist <ptr i8>))))
          (if (!= (cast new_slot_ids i64) (: 0 i64)) (block (call qdb_free (cast new_slot_ids <ptr i8>))))
          (if (!= (cast new_group_keys i64) (: 0 i64)) (block (call qdb_free (cast new_group_keys <ptr i8>))))
          (if (!= (cast new_counts i64) (: 0 i64)) (block (call qdb_free (cast new_counts <ptr i8>))))
          (if (!= (cast new_sums i64) (: 0 i64)) (block (call qdb_free (cast new_sums <ptr i8>))))
          (return #f)))
      (var i i64)
      (= i (: 0 i64))
      (while (< i new_capacity)
        (block
          (= new_keys [i] (: 0 i64))
          (= new_dist [i] (: -1 i64))
          (= new_slot_ids [i] (: -1 i64))
          (= new_group_keys [i] (: 0 i64))
          (= new_counts [i] (: 0 i64))
          (= new_sums [i] (: 0 i64))
          (= i (+ i (: 1 i64)))))
      (var old_keys = (field ht Keys))
      (var old_dist = (field ht Dist))
      (var old_slot_ids = (field ht SlotId))
      (var old_group_keys = (field ht GroupKeys))
      (var agg_buffers = (field ht AggBuffers))
      (var old_counts = (index agg_buffers (: 0 i64)))
      (var old_sums = (index agg_buffers (: 1 i64)))
      (var old_capacity = (field ht Capacity))
      (var size = (field ht Size))
      (= i (: 0 i64))
      (while (< i old_capacity)
        (block
          (if (!= (index old_dist i) (: -1 i64))
            (block
              (if (! (call count_insert_existing new_keys new_dist new_slot_ids
                      new_capacity (index old_keys i) (index old_slot_ids i)))
                (block
                  (call qdb_free (cast new_keys <ptr i8>))
                  (call qdb_free (cast new_dist <ptr i8>))
                  (call qdb_free (cast new_slot_ids <ptr i8>))
                  (call qdb_free (cast new_group_keys <ptr i8>))
                  (call qdb_free (cast new_counts <ptr i8>))
                  (call qdb_free (cast new_sums <ptr i8>))
                  (return #f)))))
          (= i (+ i (: 1 i64)))))
      (= i (: 0 i64))
      (while (< i size)
        (block
          (= new_group_keys [i] (index old_group_keys i))
          (= new_counts [i] (index old_counts i))
          (= new_sums [i] (index old_sums i))
          (= i (+ i (: 1 i64)))))
      (= agg_buffers [(: 0 i64)] new_counts)
      (= agg_buffers [(: 1 i64)] new_sums)
      (field_assign ht Keys new_keys)
      (field_assign ht Dist new_dist)
      (field_assign ht SlotId new_slot_ids)
      (field_assign ht GroupKeys new_group_keys)
      (field_assign ht Capacity new_capacity)
      (call qdb_free (cast old_keys <ptr i8>))
      (call qdb_free (cast old_dist <ptr i8>))
      (call qdb_free (cast old_slot_ids <ptr i8>))
      (call qdb_free (cast old_group_keys <ptr i8>))
      (call qdb_free (cast old_counts <ptr i8>))
      (call qdb_free (cast old_sums <ptr i8>))
      (return #t)))

  (fun count_update ((var ht <ref HashTable>) (var key i64) (var value i64)) -> i64
    (block
      (var dense_slot = (call count_lookup ht key))
      (var agg_buffers = (field ht AggBuffers))
      (var counts = (index agg_buffers (: 0 i64)))
      (var sums = (index agg_buffers (: 1 i64)))
      (if (!= dense_slot (: -1 i64))
        (block
          (= counts [dense_slot]
             (call agg_count_step (index counts dense_slot) value #f))
          (= sums [dense_slot]
             (call agg_sum_i64_step (index sums dense_slot) value #f))
          (return dense_slot)))
      (var capacity = (field ht Capacity))
      (var size = (field ht Size))
      (if (> (+ size (: 1 i64)) (- capacity (/ capacity (: 4 i64))))
        (block
          (if (> capacity (: 576460752303423487 i64)) (block (return (: -1 i64))))
          (if (! (call count_rehash ht (* capacity (: 2 i64))))
            (block (return (: -1 i64))))
          (= capacity (field ht Capacity))
          (= agg_buffers (field ht AggBuffers))
          (= counts (index agg_buffers (: 0 i64)))
          (= sums (index agg_buffers (: 1 i64)))))
      (var keys = (field ht Keys))
      (var dist = (field ht Dist))
      (var slot_ids = (field ht SlotId))
      (if (! (call count_insert_existing keys dist slot_ids capacity key size))
        (block (return (: -1 i64))))
      (var group_keys = (field ht GroupKeys))
      (= group_keys [size] key)
      (= counts [size] (: 0 i64))
      (= sums [size] (: 0 i64))
      (= counts [size] (call agg_count_step (index counts size) value #t))
      (= sums [size] (call agg_sum_i64_step (index sums size) value #t))
      (field_assign ht Size (+ size (: 1 i64)))
      (return size)))

  ;; op=0 init(capacity=key), op=1 update(key,value), op=2 lookup count,
  ;; op=3 lookup sum, op=4 destroy. This concrete function is last.
  (fun aggregation_count ((var ht <ref HashTable>)
                          (var key i64)
                          (var value i64)
                          (var op i64)) -> i64
    (block
      (return
        (if (== op (: 0 i64))
          (cast (call count_init ht key) i64)
          (if (== op (: 1 i64))
            (call count_update ht key value)
            (if (|| (== op (: 2 i64)) (== op (: 3 i64)))
              (block
                (var dense_slot = (call count_lookup ht key))
                (if (== dense_slot (: -1 i64))
                  (: -1 i64)
                  (block
                    (var agg_buffers = (field ht AggBuffers))
                    (var buffer =
                      (if (== op (: 2 i64))
                        (index agg_buffers (: 0 i64))
                        (index agg_buffers (: 1 i64))))
                    (index buffer dense_slot))))
              (block
                (call count_destroy ht)
                (: 1 i64)))))))))
