find_package(PkgConfig REQUIRED)

pkg_check_modules(GTEST gtest REQUIRED)

macro(ut name source)
    add_executable(${name} ${source})
    target_link_libraries(${name} qumirdb ${GTEST_LIBRARIES})
    target_include_directories(${name} PRIVATE ${GTEST_INCLUDE_DIRS})
    target_link_directories(${name} PRIVATE ${GTEST_LIBRARY_DIRS})
    add_test(NAME ${name} COMMAND ${name} ${ARGN} --gtest_output=xml:${CMAKE_CURRENT_BINARY_DIR}/${name}.xml)
endmacro()

ut(test_io test_io.cpp)
ut(test_sexp test_sexp.cpp)
ut(test_aggregate test_aggregate.cpp)
ut(test_aggregate_f64 test_aggregate_f64.cpp)
ut(test_filter test_filter.cpp)
ut(test_string_types test_string_types.cpp)
ut(test_string_ops test_string_ops.cpp)
ut(test_string_key_descriptor test_string_key_descriptor.cpp)
ut(test_owned_blocks test_owned_blocks.cpp)
ut(test_join test_join.cpp)
ut(test_join_node test_join_node.cpp)
ut(test_join_key test_join_key.cpp)
ut(test_project_type test_project_type.cpp)
ut(test_project_kernel test_project_kernel.cpp)
ut(test_project_e2e test_project_e2e.cpp)
ut(test_join_pipeline test_join_pipeline.cpp)
ut(test_join_exec test_join_exec.cpp)
ut(test_join_kernel test_join_kernel.cpp)
ut(test_join_planner test_join_planner.cpp)
ut(test_lexer test_lexer.cpp)
ut(test_reg test_reg.cpp ${CMAKE_SOURCE_DIR}/test/regtest)
ut(test_equijoin test_equijoin.cpp)
ut(test_sort test_sort.cpp)
