find_package(PkgConfig REQUIRED)

pkg_check_modules(GTEST gtest REQUIRED)

macro(ut name source)
    add_executable(${name} ${source})
    target_link_libraries(${name} qumirdb ${GTEST_LIBRARIES})
    target_include_directories(${name} PRIVATE ${GTEST_INCLUDE_DIRS})
    target_link_directories(${name} PRIVATE ${GTEST_LIBRARY_DIRS})
    add_test(NAME ${name} COMMAND ${name} ${ARGN} --gtest_output=xml:${CMAKE_CURRENT_BINARY_DIR}/${name}.xml)
endmacro()

ut(test_io test_io.cpp)
ut(test_sexp test_sexp.cpp)
ut(test_aggregation test_aggregation.cpp ${CMAKE_SOURCE_DIR}/qdb/kernel/aggregation)
ut(test_aggregate test_aggregate.cpp)
ut(test_string_types test_string_types.cpp)
ut(test_string_ops test_string_ops.cpp)
ut(test_string_key_descriptor test_string_key_descriptor.cpp)
ut(test_owned_blocks test_owned_blocks.cpp)
ut(test_dual_key_upsert test_dual_key_upsert.cpp)
ut(test_join test_join.cpp)
