#include <gtest/gtest.h>

#include <qumir/codegen/llvm/llvm_initializer.h>
#include <qumir/runner/runner_llvm.h>

#include <qdb/io/io.h>
#include <qdb/kernel/gen.h>
#include <qdb/kernel/lib.h>
#include <qdb/modules/qumirdb.h>

#include <algorithm>
#include <array>
#include <filesystem>
#include <fstream>
#include <limits>
#include <memory>
#include <sstream>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <vector>

namespace {

std::filesystem::path KernelDir = "qdb/kernel/aggregation";

std::string ReadKernel(const std::string& name) {
    const auto path = KernelDir / name;
    std::ifstream input(path);
    if (!input) {
        throw std::runtime_error("cannot open aggregation kernel: " + path.string());
    }
    std::ostringstream source;
    source << input.rdbuf();
    return source.str();
}

std::unique_ptr<NQumir::TLLVMRunner> CompileKernel(
    const std::string& name,
    void*& entry,
    std::string& error)
{
    NQumir::TLLVMRunnerOptions options;
    options.CoreInput = true;
    options.ResolveCoreInput = true;
    options.AllowOverloads = true;
    options.NativeCode = true;

    auto runner = std::make_unique<NQumir::TLLVMRunner>(options);
    runner->RegisterModule(std::make_shared<NQumir::NRegistry::QumirDbModule>(), true);
    entry = runner->CompileKernel(ReadKernel(name), &error);
    return runner;
}

// Builds agg_dispatch (L2's GenAggregateKernelAst) merged with count.oz's
// library (L1's MergeKernelLibrary) and compiles it via CompileKernelAst.
std::unique_ptr<NQumir::TLLVMRunner> CompileAggregateDispatch(
    const std::unordered_map<std::string, int32_t>& fieldIndices,
    const std::string& keyField,
    const std::optional<std::string>& argField,
    void*& entry,
    std::string& error)
{
    using namespace NQumir::NAst;

    auto dbModule = std::make_shared<NQumir::NRegistry::QumirDbModule>();
    TTypePtr columnType, rowSetType, hashTableType;
    for (const auto& et : dbModule->ExternalTypes()) {
        if (et.Name == "TColumn") columnType = et.Type;
        else if (et.Name == "TRowSet") rowSetType = et.Type;
        else if (et.Name == "HashTable") hashTableType = et.Type;
    }

    auto entryAst = NQqb::NKernel::GenAggregateKernelAst(
        fieldIndices, keyField, argField, columnType, rowSetType, hashTableType);
    auto entryFun = TMaybeNode<TBlockExpr>(entryAst).Cast()->Stmts.front();

    auto library = NQqb::NKernel::ParseFunctionLibrary(
        ReadKernel("count.oz"), {"aggregate_batch", "aggregation_count"});
    if (!library) {
        throw std::runtime_error("count.oz: " + library.error().ToString());
    }

    NQumir::TLLVMRunnerOptions options;
    options.CoreInput = true;
    options.NativeCode = true;
    options.AllowOverloads = true;

    auto runner = std::make_unique<NQumir::TLLVMRunner>(options);
    runner->RegisterModule(dbModule, true);

    auto merged = NQqb::NKernel::MergeKernelLibrary(*library, std::move(entryFun));
    entry = runner->CompileKernelAst(merged, &error);
    return runner;
}

// Builds reduce_smoke(i64 prev, i64 value, i64 is_new_flag, <ptr i64> out),
// which for i in [0, numReducers) does
//   out[i] = reduce_i(prev, value, is_new_flag != 0)
// — numReducers static, direct, by-name calls to the reduce_0..reduce_{N-1}
// functions generated by GenReducerFunDecls. This mirrors the pattern the
// future generated agg_update will use to update N aggregate buffers per
// row, with no function pointers and no dispatch on Func.
NQumir::NAst::TExprPtr GenReduceSmokeEntry(size_t numReducers) {
    using namespace NQumir::NAst;
    NQumir::TLocation loc{};

    auto i64Type = std::make_shared<TIntegerType>();
    auto boolType = std::make_shared<TBoolType>();
    auto ptrI64Type = std::make_shared<TPointerType>(i64Type);

    auto ident = [&](const std::string& name) {
        return std::make_shared<TIdentExpr>(loc, name);
    };
    auto numI64 = [&](int64_t value) -> TExprPtr {
        auto expr = std::make_shared<TNumberExpr>(loc, value);
        expr->Type = i64Type;
        return expr;
    };

    std::vector<TParam> params = {
        std::make_shared<TVarStmt>(loc, "prev", i64Type),
        std::make_shared<TVarStmt>(loc, "value", i64Type),
        std::make_shared<TVarStmt>(loc, "is_new_flag", i64Type),
        std::make_shared<TVarStmt>(loc, "out", ptrI64Type),
    };

    std::vector<TExprPtr> stmts;
    stmts.push_back(std::make_shared<TVarStmt>(loc, "is_new", boolType));
    stmts.push_back(std::make_shared<TAssignExpr>(loc, "is_new",
        std::make_shared<TBinaryExpr>(loc, TOperator("!="), ident("is_new_flag"), numI64(0))));

    for (size_t i = 0; i < numReducers; ++i) {
        auto call = std::make_shared<TCallExpr>(loc,
            ident("reduce_" + std::to_string(i)),
            std::vector<TExprPtr>{ident("prev"), ident("value"), ident("is_new")});
        stmts.push_back(std::make_shared<TArrayAssignExpr>(loc, "out",
            std::vector<TExprPtr>{numI64(static_cast<int64_t>(i))}, call));
    }

    auto body = std::make_shared<TBlockExpr>(loc, std::move(stmts));
    return std::make_shared<TFunDecl>(loc, "reduce_smoke", std::move(params), body,
        std::make_shared<TVoidType>());
}

// Generates reduce_0..reduce_{N-1} (GenReducerFunDecls) for `funcs`, merges
// them with a reduce_smoke entry (GenReduceSmokeEntry) via L1, and compiles
// the result. No HashTable/TRowSet/count.oz involved — this exercises only
// the predefined-name reducer generation + static AST injection.
std::unique_ptr<NQumir::TLLVMRunner> CompileReducerSmoke(
    const std::vector<std::string>& funcs,
    void*& entry,
    std::string& error)
{
    auto reducers = NQqb::NKernel::GenReducerFunDecls(funcs);
    auto smokeEntry = GenReduceSmokeEntry(funcs.size());

    NQumir::TLLVMRunnerOptions options;
    options.CoreInput = true;
    options.NativeCode = true;
    options.AllowOverloads = true;

    auto runner = std::make_unique<NQumir::TLLVMRunner>(options);

    auto merged = NQqb::NKernel::MergeKernelLibrary(std::move(reducers), std::move(smokeEntry));
    entry = runner->CompileKernelAst(merged, &error);
    return runner;
}

// Generates apply_smoke(<ptr <ptr i64>> agg_buffers, i64 dense_slot,
// i64 value, i64 is_new_flag), which calls
//   agg_apply_reducers(agg_buffers, dense_slot, value, is_new_flag != 0)
// — the single per-query generated function (GenApplyReducersFunDecl) that
// the future NumAggs-generic agg_update (L2b) will call to update all N
// aggregate buffers for one dense slot.
NQumir::NAst::TExprPtr GenApplyReducersSmokeEntry() {
    using namespace NQumir::NAst;
    NQumir::TLocation loc{};

    auto i64Type = std::make_shared<TIntegerType>();
    auto boolType = std::make_shared<TBoolType>();
    auto ptrI64Type = std::make_shared<TPointerType>(i64Type);
    auto ptrPtrI64Type = std::make_shared<TPointerType>(ptrI64Type);

    auto ident = [&](const std::string& name) {
        return std::make_shared<TIdentExpr>(loc, name);
    };
    auto numI64 = [&](int64_t value) -> TExprPtr {
        auto expr = std::make_shared<TNumberExpr>(loc, value);
        expr->Type = i64Type;
        return expr;
    };

    std::vector<TParam> params = {
        std::make_shared<TVarStmt>(loc, "agg_buffers", ptrPtrI64Type),
        std::make_shared<TVarStmt>(loc, "dense_slot", i64Type),
        std::make_shared<TVarStmt>(loc, "value", i64Type),
        std::make_shared<TVarStmt>(loc, "is_new_flag", i64Type),
    };

    std::vector<TExprPtr> stmts;
    stmts.push_back(std::make_shared<TVarStmt>(loc, "is_new", boolType));
    stmts.push_back(std::make_shared<TAssignExpr>(loc, "is_new",
        std::make_shared<TBinaryExpr>(loc, TOperator("!="), ident("is_new_flag"), numI64(0))));
    stmts.push_back(std::make_shared<TCallExpr>(loc, ident("agg_apply_reducers"),
        std::vector<TExprPtr>{ident("agg_buffers"), ident("dense_slot"), ident("value"), ident("is_new")}));

    auto body = std::make_shared<TBlockExpr>(loc, std::move(stmts));
    return std::make_shared<TFunDecl>(loc, "apply_smoke", std::move(params), body,
        std::make_shared<TVoidType>());
}

// Generates reduce_0..reduce_{N-1} (GenReducerFunDecls) plus
// agg_apply_reducers (GenApplyReducersFunDecl) for `funcs`, merges them with
// an apply_smoke entry (GenApplyReducersSmokeEntry) via L1, and compiles the
// result. No HashTable/TRowSet/count.oz involved — exercises the single
// per-query generated function that updates all N aggregate buffers for one
// dense slot, by static name, with no function pointers.
std::unique_ptr<NQumir::TLLVMRunner> CompileApplyReducersSmoke(
    const std::vector<std::string>& funcs,
    void*& entry,
    std::string& error)
{
    auto library = NQqb::NKernel::GenReducerFunDecls(funcs);
    library.push_back(NQqb::NKernel::GenApplyReducersFunDecl(funcs.size()));
    auto smokeEntry = GenApplyReducersSmokeEntry();

    NQumir::TLLVMRunnerOptions options;
    options.CoreInput = true;
    options.NativeCode = true;
    options.AllowOverloads = true;

    auto runner = std::make_unique<NQumir::TLLVMRunner>(options);

    auto merged = NQqb::NKernel::MergeKernelLibrary(std::move(library), std::move(smokeEntry));
    entry = runner->CompileKernelAst(merged, &error);
    return runner;
}

struct THashTable {
    int64_t* Keys = nullptr;
    int64_t* Dist = nullptr;
    int64_t* SlotId = nullptr;
    int64_t* GroupKeys = nullptr;
    int64_t** AggBuffers = nullptr;
    int64_t* Scratch = nullptr;
    int64_t* Scratch2 = nullptr;
    int64_t* QueryKey = nullptr;
    int64_t Capacity = 0;
    int64_t Size = 0;
    int64_t NumAggs = 0;
    int64_t NumKeys = 0;
};

struct TPairI64Key {
    int64_t First;
    int64_t Second;

    bool operator==(const TPairI64Key&) const = default;
};

static_assert(sizeof(THashTable) == 96);

uint64_t HashI64(int64_t key) {
    uint64_t h = static_cast<uint64_t>(key);
    h ^= h >> 12;
    h ^= h << 25;
    h ^= h >> 27;
    return h * UINT64_C(2685821657736338717);
}

std::vector<int64_t> KeysForHome(int64_t home, int64_t capacity, size_t count) {
    std::vector<int64_t> result;
    for (int64_t key = 0; result.size() < count; ++key) {
        if (static_cast<int64_t>(HashI64(key) & static_cast<uint64_t>(capacity - 1)) == home) {
            result.push_back(key);
        }
    }
    return result;
}

} // namespace

TEST(AggregationKernel, GenericKeyDispatchInstantiatesI64) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("generic_key_smoke.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TSmokeFn = int64_t(*)(int64_t);
    auto smoke = reinterpret_cast<TSmokeFn>(entry);
    EXPECT_EQ(smoke(0), 0);
    EXPECT_EQ(smoke(42), 42);
    EXPECT_EQ(smoke(-17), -17);
}

TEST(AggregationKernel, GenericKeyEqualityDispatchesToI64Overload) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("generic_key_equal.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TEqualFn = bool(*)(int64_t, int64_t);
    auto equal = reinterpret_cast<TEqualFn>(entry);
    EXPECT_TRUE(equal(0, 0));
    EXPECT_TRUE(equal(-17, -17));
    EXPECT_FALSE(equal(1, -1));
    EXPECT_FALSE(equal(42, 43));
}

TEST(AggregationKernel, GenericHashDispatchesToConcretePairOverload) {
    void* i64Entry = nullptr;
    void* pairEntry = nullptr;
    std::string error;
    auto i64Runner = CompileKernel("generic_dispatch_i64.oz", i64Entry, error);
    ASSERT_NE(i64Entry, nullptr) << error;
    auto pairRunner = CompileKernel("generic_dispatch_pair_i64.oz", pairEntry, error);
    ASSERT_NE(pairEntry, nullptr) << error;

    using TI64DispatchFn = int64_t(*)(int64_t);
    using TPairDispatchFn = int64_t(*)(TPairI64Key);
    auto dispatchI64 = reinterpret_cast<TI64DispatchFn>(i64Entry);
    auto dispatchPair = reinterpret_cast<TPairDispatchFn>(pairEntry);
    EXPECT_EQ(dispatchI64(7), 1007);
    EXPECT_EQ(dispatchPair({7, 13}), 713);
}

TEST(AggregationKernel, GenericPairRobinHoodHandlesCollisionsDuplicatesAndReducers) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("generic_pair_fixed.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TPairBatchFn = int64_t(*)(
        TPairI64Key*, int64_t*, int64_t*, int64_t, int64_t*, TPairI64Key*,
        int64_t*, int64_t*, TPairI64Key*, int64_t*, int64_t);
    auto process = reinterpret_cast<TPairBatchFn>(entry);
    constexpr int64_t capacity = 8;
    std::array<TPairI64Key, capacity> keys{};
    std::array<int64_t, capacity> dist{};
    std::array<int64_t, capacity> slotIds{};
    std::array<TPairI64Key, capacity> groupKeys{};
    std::array<int64_t, capacity> counts{};
    std::array<int64_t, capacity> sums{};
    dist.fill(-1);
    slotIds.fill(-1);
    int64_t size = 0;

    std::array<TPairI64Key, 7> input = {
        TPairI64Key{1, 10}, {2, 20}, {1, 10}, {3, 30}, {4, 40}, {2, 20}, {5, 50}};
    std::array<int64_t, 7> values = {5, 7, 11, 13, 17, -2, 19};
    ASSERT_EQ(process(keys.data(), dist.data(), slotIds.data(), capacity, &size,
                      groupKeys.data(), counts.data(), sums.data(), input.data(),
                      values.data(), input.size()), 5);

    EXPECT_EQ(size, 5);
    EXPECT_EQ(groupKeys[0], (TPairI64Key{1, 10}));
    EXPECT_EQ(groupKeys[1], (TPairI64Key{2, 20}));
    EXPECT_EQ(groupKeys[2], (TPairI64Key{3, 30}));
    EXPECT_EQ(groupKeys[3], (TPairI64Key{4, 40}));
    EXPECT_EQ(groupKeys[4], (TPairI64Key{5, 50}));
    EXPECT_EQ((std::array<int64_t, 5>{counts[0], counts[1], counts[2], counts[3], counts[4]}),
              (std::array<int64_t, 5>{2, 2, 1, 1, 1}));
    EXPECT_EQ((std::array<int64_t, 5>{sums[0], sums[1], sums[2], sums[3], sums[4]}),
              (std::array<int64_t, 5>{16, 5, 13, 17, 19}));

    std::array<bool, capacity> seen{};
    for (int64_t slot = 0; slot < capacity; ++slot) {
        if (dist[slot] >= 0) {
            ASSERT_GE(slotIds[slot], 0);
            ASSERT_LT(slotIds[slot], size);
            EXPECT_FALSE(seen[slotIds[slot]]);
            seen[slotIds[slot]] = true;
        }
    }
    for (int64_t slot = 0; slot < size; ++slot) {
        EXPECT_TRUE(seen[slot]);
    }
}

TEST(AggregationKernel, GenericPairRehashPreservesSlotsAndAggregationState) {
    void* processEntry = nullptr;
    void* rehashEntry = nullptr;
    std::string error;
    auto processRunner = CompileKernel("generic_pair_fixed.oz", processEntry, error);
    ASSERT_NE(processEntry, nullptr) << error;
    auto rehashRunner = CompileKernel("generic_pair_rehash.oz", rehashEntry, error);
    ASSERT_NE(rehashEntry, nullptr) << error;

    using TPairBatchFn = int64_t(*)(
        TPairI64Key*, int64_t*, int64_t*, int64_t, int64_t*, TPairI64Key*,
        int64_t*, int64_t*, TPairI64Key*, int64_t*, int64_t);
    using TPairRehashFn = int64_t(*)(
        TPairI64Key*, int64_t*, int64_t*, int64_t, int64_t, TPairI64Key*,
        int64_t*, int64_t*, TPairI64Key*, int64_t*, int64_t*, int64_t,
        TPairI64Key*, int64_t*, int64_t*);
    auto process = reinterpret_cast<TPairBatchFn>(processEntry);
    auto rehash = reinterpret_cast<TPairRehashFn>(rehashEntry);

    constexpr int64_t oldCapacity = 8;
    constexpr int64_t newCapacity = 16;
    std::array<TPairI64Key, oldCapacity> oldKeys{};
    std::array<int64_t, oldCapacity> oldDist{};
    std::array<int64_t, oldCapacity> oldSlotIds{};
    std::array<TPairI64Key, oldCapacity> oldGroupKeys{};
    std::array<int64_t, oldCapacity> oldCounts{};
    std::array<int64_t, oldCapacity> oldSums{};
    oldDist.fill(-1);
    oldSlotIds.fill(-1);
    int64_t size = 0;
    std::array<TPairI64Key, 5> initialKeys = {
        TPairI64Key{1, 2}, {3, 4}, {5, 6}, {1, 2}, {7, 8}};
    std::array<int64_t, 5> initialValues = {10, 20, 30, 5, 40};
    ASSERT_EQ(process(oldKeys.data(), oldDist.data(), oldSlotIds.data(), oldCapacity,
                      &size, oldGroupKeys.data(), oldCounts.data(), oldSums.data(),
                      initialKeys.data(), initialValues.data(), initialKeys.size()), 4);

    std::array<TPairI64Key, newCapacity> newKeys{};
    std::array<int64_t, newCapacity> newDist{};
    std::array<int64_t, newCapacity> newSlotIds{};
    std::array<TPairI64Key, newCapacity> newGroupKeys{};
    std::array<int64_t, newCapacity> newCounts{};
    std::array<int64_t, newCapacity> newSums{};
    ASSERT_EQ(rehash(oldKeys.data(), oldDist.data(), oldSlotIds.data(), oldCapacity,
                     size, oldGroupKeys.data(), oldCounts.data(), oldSums.data(),
                     newKeys.data(), newDist.data(), newSlotIds.data(), newCapacity,
                     newGroupKeys.data(), newCounts.data(), newSums.data()), size);

    EXPECT_EQ(newGroupKeys[0], (TPairI64Key{1, 2}));
    EXPECT_EQ(newGroupKeys[1], (TPairI64Key{3, 4}));
    EXPECT_EQ(newGroupKeys[2], (TPairI64Key{5, 6}));
    EXPECT_EQ(newGroupKeys[3], (TPairI64Key{7, 8}));
    EXPECT_EQ((std::array<int64_t, 4>{newCounts[0], newCounts[1], newCounts[2], newCounts[3]}),
              (std::array<int64_t, 4>{2, 1, 1, 1}));
    EXPECT_EQ((std::array<int64_t, 4>{newSums[0], newSums[1], newSums[2], newSums[3]}),
              (std::array<int64_t, 4>{15, 20, 30, 40}));

    std::array<TPairI64Key, 3> moreKeys = {
        TPairI64Key{3, 4}, {9, 10}, {11, 12}};
    std::array<int64_t, 3> moreValues = {-7, 50, 60};
    ASSERT_EQ(process(newKeys.data(), newDist.data(), newSlotIds.data(), newCapacity,
                      &size, newGroupKeys.data(), newCounts.data(), newSums.data(),
                      moreKeys.data(), moreValues.data(), moreKeys.size()), 6);
    EXPECT_EQ(newGroupKeys[4], (TPairI64Key{9, 10}));
    EXPECT_EQ(newGroupKeys[5], (TPairI64Key{11, 12}));
    EXPECT_EQ(newCounts[1], 2);
    EXPECT_EQ(newSums[1], 13);
    EXPECT_EQ(newCounts[4], 1);
    EXPECT_EQ(newSums[4], 50);

    std::array<bool, newCapacity> seen{};
    for (int64_t slot = 0; slot < newCapacity; ++slot) {
        if (newDist[slot] >= 0) {
            ASSERT_GE(newSlotIds[slot], 0);
            ASSERT_LT(newSlotIds[slot], size);
            EXPECT_FALSE(seen[newSlotIds[slot]]);
            seen[newSlotIds[slot]] = true;
        }
    }
    for (int64_t slot = 0; slot < size; ++slot) {
        EXPECT_TRUE(seen[slot]);
    }
}

TEST(AggregationKernel, GenericKeyPointerReadWriteAndSwap) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("generic_key_memory.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TMemoryFn = int64_t(*)(int64_t*, int64_t, int64_t, int64_t);
    auto mutate = reinterpret_cast<TMemoryFn>(entry);
    int64_t keys[] = {10, 20, 30};

    EXPECT_EQ(mutate(keys, 0, 2, 99), 30);
    EXPECT_EQ(keys[0], 30);
    EXPECT_EQ(keys[1], 20);
    EXPECT_EQ(keys[2], 99);
}

TEST(AggregationKernel, ConcreteI64PointerWriteControl) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("concrete_key_memory.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TMemoryFn = int64_t(*)(int64_t*, int64_t, int64_t);
    auto write = reinterpret_cast<TMemoryFn>(entry);
    int64_t keys[] = {10, 20, 30};

    EXPECT_EQ(write(keys, 1, 77), 77);
    EXPECT_EQ(keys[0], 10);
    EXPECT_EQ(keys[1], 77);
    EXPECT_EQ(keys[2], 30);
}

TEST(AggregationKernel, I64HashHasStableBoundaryVectors) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("i64_hash.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using THashFn = int64_t(*)(int64_t);
    auto hash = reinterpret_cast<THashFn>(entry);
    EXPECT_EQ(hash(0), 0);
    EXPECT_EQ(hash(1), 5180492295206395165LL);
    EXPECT_EQ(hash(-1), -491796270583644160LL);
    EXPECT_EQ(hash(std::numeric_limits<int64_t>::min()), -1079387622448562176LL);
    EXPECT_EQ(hash(std::numeric_limits<int64_t>::max()), -245898135291822080LL);
}

TEST(AggregationKernel, HomeSlotAndNextIndexUsePowerOfTwoMask) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("slot_math.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TSlotMathFn = int64_t(*)(int64_t, int64_t, int64_t);
    auto slotMath = reinterpret_cast<TSlotMathFn>(entry);
    constexpr std::array<int64_t, 4> capacities = {4, 8, 16, 32};
    constexpr std::array<int64_t, 5> hashes = {
        0, 1, -1, 17, std::numeric_limits<int64_t>::min()};
    for (int64_t capacity : capacities) {
        for (int64_t hash : hashes) {
            const auto home = slotMath(hash, capacity, 0);
            EXPECT_GE(home, 0);
            EXPECT_LT(home, capacity);
            EXPECT_EQ(home, hash & (capacity - 1));
        }
        EXPECT_EQ(slotMath(capacity - 2, capacity, 1), capacity - 1);
        EXPECT_EQ(slotMath(capacity - 1, capacity, 1), 0);
    }
}

TEST(AggregationKernel, ReadOnlyRobinHoodLookup) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("lookup.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TLookupFn = int64_t(*)(int64_t*, int64_t*, int64_t, int64_t);
    auto lookup = reinterpret_cast<TLookupFn>(entry);
    constexpr int64_t capacity = 8;
    std::array<int64_t, capacity> keys{};
    std::array<int64_t, capacity> dist{};
    dist.fill(-1);

    EXPECT_EQ(lookup(keys.data(), dist.data(), capacity, 42), -1);

    const auto home3 = KeysForHome(3, capacity, 3);
    keys[3] = home3[0];
    dist[3] = 0;
    EXPECT_EQ(lookup(keys.data(), dist.data(), capacity, home3[0]), 3);

    keys[4] = home3[1];
    dist[4] = 1;
    keys[5] = home3[2];
    dist[5] = 2;
    EXPECT_EQ(lookup(keys.data(), dist.data(), capacity, home3[2]), 5);

    keys.fill(0);
    dist.fill(-1);
    const auto home7 = KeysForHome(7, capacity, 2);
    keys[7] = home7[0];
    dist[7] = 0;
    keys[0] = home7[1];
    dist[0] = 1;
    EXPECT_EQ(lookup(keys.data(), dist.data(), capacity, home7[1]), 0);

    keys.fill(0);
    dist.fill(-1);
    const auto home2 = KeysForHome(2, capacity, 2);
    const auto home3Single = KeysForHome(3, capacity, 1);
    keys[2] = home2[0];
    dist[2] = 0;
    keys[3] = home3Single[0];
    dist[3] = 0;
    EXPECT_EQ(lookup(keys.data(), dist.data(), capacity, home2[1]), -1);

    for (int64_t i = 0; i < capacity; ++i) {
        keys[i] = i + 1000;
        dist[i] = capacity;
    }
    EXPECT_EQ(lookup(keys.data(), dist.data(), capacity, -999), -1);
}

TEST(AggregationKernel, FixedCapacityRobinHoodInsertion) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("insert_fixed.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TInsertFn = int64_t(*)(int64_t*, int64_t*, int64_t, int64_t);
    auto insert = reinterpret_cast<TInsertFn>(entry);
    constexpr int64_t capacity = 8;
    std::array<int64_t, capacity> keys{};
    std::array<int64_t, capacity> dist{};
    dist.fill(-1);

    const auto home4 = KeysForHome(4, capacity, 3);
    EXPECT_EQ(insert(keys.data(), dist.data(), capacity, home4[0]), 4);
    EXPECT_EQ(keys[4], home4[0]);
    EXPECT_EQ(dist[4], 0);

    const auto beforeKeys = keys;
    const auto beforeDist = dist;
    EXPECT_EQ(insert(keys.data(), dist.data(), capacity, home4[0]), 4);
    EXPECT_EQ(keys, beforeKeys);
    EXPECT_EQ(dist, beforeDist);

    EXPECT_EQ(insert(keys.data(), dist.data(), capacity, home4[1]), 5);
    EXPECT_EQ(keys[5], home4[1]);
    EXPECT_EQ(dist[5], 1);

    keys.fill(0);
    dist.fill(-1);
    const auto home5 = KeysForHome(5, capacity, 1);
    const auto home6 = KeysForHome(6, capacity, 1);
    keys[4] = home4[0];
    dist[4] = 0;
    keys[5] = home5[0];
    dist[5] = 0;
    keys[6] = home6[0];
    dist[6] = 0;
    EXPECT_EQ(insert(keys.data(), dist.data(), capacity, home4[1]), 5);
    EXPECT_EQ(keys[4], home4[0]);
    EXPECT_EQ(keys[5], home4[1]);
    EXPECT_EQ(keys[6], home5[0]);
    EXPECT_EQ(keys[7], home6[0]);
    EXPECT_EQ(dist[4], 0);
    EXPECT_EQ(dist[5], 1);
    EXPECT_EQ(dist[6], 1);
    EXPECT_EQ(dist[7], 1);

    keys.fill(0);
    dist.fill(-1);
    const auto home7 = KeysForHome(7, capacity, 2);
    const auto home0 = KeysForHome(0, capacity, 1);
    keys[7] = home7[0];
    dist[7] = 0;
    keys[0] = home0[0];
    dist[0] = 0;
    EXPECT_EQ(insert(keys.data(), dist.data(), capacity, home7[1]), 0);
    EXPECT_EQ(keys[7], home7[0]);
    EXPECT_EQ(keys[0], home7[1]);
    EXPECT_EQ(keys[1], home0[0]);
    EXPECT_EQ(dist[0], 1);
    EXPECT_EQ(dist[1], 1);

    for (int64_t i = 0; i < capacity; ++i) {
        keys[i] = i;
        dist[i] = capacity;
    }
    EXPECT_EQ(insert(keys.data(), dist.data(), capacity, 123456), -1);
}

TEST(AggregationKernel, FixedCapacityTableMaintainsInvariants) {
    void* insertEntry = nullptr;
    std::string insertError;
    auto insertRunner = CompileKernel("insert_fixed.oz", insertEntry, insertError);
    ASSERT_NE(insertEntry, nullptr) << insertError;

    void* checkEntry = nullptr;
    std::string checkError;
    auto checkRunner = CompileKernel("check_invariants.oz", checkEntry, checkError);
    ASSERT_NE(checkEntry, nullptr) << checkError;

    using TInsertFn = int64_t(*)(int64_t*, int64_t*, int64_t, int64_t);
    using TCheckFn = bool(*)(int64_t*, int64_t*, int64_t);
    auto insert = reinterpret_cast<TInsertFn>(insertEntry);
    auto check = reinterpret_cast<TCheckFn>(checkEntry);
    constexpr int64_t capacity = 16;
    std::array<int64_t, capacity> keys{};
    std::array<int64_t, capacity> dist{};
    dist.fill(-1);

    constexpr std::array<int64_t, 12> input = {
        0, 1, -1, 17, 33, 49, 65, 81, 97, 113, 129, 145};
    EXPECT_TRUE(check(keys.data(), dist.data(), capacity));
    for (int64_t key : input) {
        ASSERT_NE(insert(keys.data(), dist.data(), capacity, key), -1);
        EXPECT_TRUE(check(keys.data(), dist.data(), capacity)) << "after key " << key;
    }

    auto corrupted = dist;
    for (int64_t i = 0; i < capacity; ++i) {
        if (corrupted[i] >= 0) {
            ++corrupted[i];
            break;
        }
    }
    EXPECT_FALSE(check(keys.data(), corrupted.data(), capacity));
}

TEST(AggregationKernel, StableDenseSlotIdsSurviveDisplacement) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("insert_slot_id.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TInsertFn = int64_t(*)(
        int64_t*, int64_t*, int64_t*, int64_t, int64_t*, int64_t);
    auto insert = reinterpret_cast<TInsertFn>(entry);
    constexpr int64_t capacity = 8;
    std::array<int64_t, capacity> keys{};
    std::array<int64_t, capacity> dist{};
    std::array<int64_t, capacity> slotIds{};
    dist.fill(-1);
    slotIds.fill(-1);
    int64_t size = 0;

    const auto home4 = KeysForHome(4, capacity, 2);
    const auto home5 = KeysForHome(5, capacity, 1);
    const auto home6 = KeysForHome(6, capacity, 1);
    EXPECT_EQ(insert(keys.data(), dist.data(), slotIds.data(), capacity, &size, home4[0]), 0);
    EXPECT_EQ(insert(keys.data(), dist.data(), slotIds.data(), capacity, &size, home5[0]), 1);
    EXPECT_EQ(insert(keys.data(), dist.data(), slotIds.data(), capacity, &size, home6[0]), 2);
    EXPECT_EQ(size, 3);

    EXPECT_EQ(insert(keys.data(), dist.data(), slotIds.data(), capacity, &size, home4[1]), 3);
    EXPECT_EQ(size, 4);
    EXPECT_EQ(keys[4], home4[0]);
    EXPECT_EQ(slotIds[4], 0);
    EXPECT_EQ(keys[5], home4[1]);
    EXPECT_EQ(slotIds[5], 3);
    EXPECT_EQ(keys[6], home5[0]);
    EXPECT_EQ(slotIds[6], 1);
    EXPECT_EQ(keys[7], home6[0]);
    EXPECT_EQ(slotIds[7], 2);

    EXPECT_EQ(insert(keys.data(), dist.data(), slotIds.data(), capacity, &size, home5[0]), 1);
    EXPECT_EQ(size, 4);

    std::array<bool, capacity> seen{};
    for (int64_t i = 0; i < capacity; ++i) {
        if (dist[i] >= 0) {
            ASSERT_GE(slotIds[i], 0);
            ASSERT_LT(slotIds[i], size);
            EXPECT_FALSE(seen[slotIds[i]]);
            seen[slotIds[i]] = true;
        }
    }
    for (int64_t slot = 0; slot < size; ++slot) {
        EXPECT_TRUE(seen[slot]);
    }
}

TEST(AggregationKernel, OzTableLifecycleAllocatesInitializesAndDestroys) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("table_lifecycle.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TLifecycleFn = int64_t(*)(THashTable*, int64_t, int64_t);
    auto lifecycle = reinterpret_cast<TLifecycleFn>(entry);
    THashTable table;

    ASSERT_TRUE(lifecycle(&table, 8, 0));
    ASSERT_NE(table.Keys, nullptr);
    ASSERT_NE(table.Dist, nullptr);
    ASSERT_NE(table.SlotId, nullptr);
    EXPECT_EQ(table.Capacity, 8);
    EXPECT_EQ(table.Size, 0);
    EXPECT_EQ(table.NumKeys, 1);
    for (int64_t i = 0; i < table.Capacity; ++i) {
        EXPECT_EQ(table.Keys[i], 0);
        EXPECT_EQ(table.Dist[i], -1);
        EXPECT_EQ(table.SlotId[i], -1);
    }

    EXPECT_TRUE(lifecycle(&table, 0, 1));
    EXPECT_EQ(table.Keys, nullptr);
    EXPECT_EQ(table.Dist, nullptr);
    EXPECT_EQ(table.SlotId, nullptr);
    EXPECT_EQ(table.Capacity, 0);
    EXPECT_EQ(table.Size, 0);
}

TEST(AggregationKernel, OzTableLifecycleRejectsAllocationSizeOverflow) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("table_lifecycle.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TLifecycleFn = int64_t(*)(THashTable*, int64_t, int64_t);
    auto lifecycle = reinterpret_cast<TLifecycleFn>(entry);
    THashTable table;
    EXPECT_FALSE(lifecycle(&table, INT64_C(1152921504606846976), 0));
    EXPECT_EQ(table.Keys, nullptr);
    EXPECT_EQ(table.Capacity, 0);
}

TEST(AggregationKernel, OzTableGrowsAndPreservesStableSlotIds) {
    void* lifecycleEntry = nullptr;
    void* growEntry = nullptr;
    void* checkEntry = nullptr;
    std::string error;
    auto lifecycleRunner = CompileKernel("table_lifecycle.oz", lifecycleEntry, error);
    ASSERT_NE(lifecycleEntry, nullptr) << error;
    auto growRunner = CompileKernel("table_grow.oz", growEntry, error);
    ASSERT_NE(growEntry, nullptr) << error;
    auto checkRunner = CompileKernel("check_invariants.oz", checkEntry, error);
    ASSERT_NE(checkEntry, nullptr) << error;

    using TLifecycleFn = int64_t(*)(THashTable*, int64_t, int64_t);
    using TGrowFn = int64_t(*)(THashTable*, int64_t, int64_t);
    using TCheckFn = bool(*)(int64_t*, int64_t*, int64_t);
    auto lifecycle = reinterpret_cast<TLifecycleFn>(lifecycleEntry);
    auto insertOrLookup = reinterpret_cast<TGrowFn>(growEntry);
    auto check = reinterpret_cast<TCheckFn>(checkEntry);

    THashTable table;
    ASSERT_TRUE(lifecycle(&table, 4, 0));
    constexpr std::array<int64_t, 20> input = {
        0, 1, -1, 17, 33, 49, 65, 81, 97, 113,
        129, 145, 161, 177, 193, 209, 225, 241, 257, 273};
    constexpr std::array<int64_t, 4> expectedCapacities = {4, 8, 16, 32};
    size_t capacityIndex = 0;

    for (size_t i = 0; i < input.size(); ++i) {
        const int64_t oldCapacity = table.Capacity;
        EXPECT_EQ(insertOrLookup(&table, input[i], 0), static_cast<int64_t>(i));
        ASSERT_EQ(table.Size, static_cast<int64_t>(i + 1));
        if (table.Capacity != oldCapacity) {
            ++capacityIndex;
            ASSERT_LT(capacityIndex, expectedCapacities.size());
            EXPECT_EQ(table.Capacity, expectedCapacities[capacityIndex]);
        }
        EXPECT_TRUE(check(table.Keys, table.Dist, table.Capacity));
        for (size_t keyIndex = 0; keyIndex <= i; ++keyIndex) {
            EXPECT_EQ(insertOrLookup(&table, input[keyIndex], 1),
                      static_cast<int64_t>(keyIndex));
        }
    }

    EXPECT_EQ(capacityIndex, expectedCapacities.size() - 1);
    const int64_t sizeBeforeDuplicate = table.Size;
    EXPECT_EQ(insertOrLookup(&table, input[3], 0), 3);
    EXPECT_EQ(table.Size, sizeBeforeDuplicate);
    EXPECT_EQ(table.Capacity, 32);

    std::array<bool, input.size()> seen{};
    for (int64_t i = 0; i < table.Capacity; ++i) {
        if (table.Dist[i] >= 0) {
            ASSERT_GE(table.SlotId[i], 0);
            ASSERT_LT(table.SlotId[i], table.Size);
            EXPECT_FALSE(seen[table.SlotId[i]]);
            seen[table.SlotId[i]] = true;
        }
    }
    for (bool present : seen) {
        EXPECT_TRUE(present);
    }

    EXPECT_TRUE(lifecycle(&table, 0, 1));
}

TEST(AggregationKernel, OzTableRehashRejectsAllocationSizeOverflow) {
    void* lifecycleEntry = nullptr;
    void* growEntry = nullptr;
    std::string error;
    auto lifecycleRunner = CompileKernel("table_lifecycle.oz", lifecycleEntry, error);
    ASSERT_NE(lifecycleEntry, nullptr) << error;
    auto growRunner = CompileKernel("table_grow.oz", growEntry, error);
    ASSERT_NE(growEntry, nullptr) << error;

    using TLifecycleFn = int64_t(*)(THashTable*, int64_t, int64_t);
    using TGrowFn = int64_t(*)(THashTable*, int64_t, int64_t);
    auto lifecycle = reinterpret_cast<TLifecycleFn>(lifecycleEntry);
    auto grow = reinterpret_cast<TGrowFn>(growEntry);
    THashTable table;
    ASSERT_TRUE(lifecycle(&table, 4, 0));
    int64_t* const oldKeys = table.Keys;
    EXPECT_FALSE(grow(&table, INT64_C(1152921504606846976), 2));
    EXPECT_EQ(table.Keys, oldKeys);
    EXPECT_EQ(table.Capacity, 4);
    EXPECT_EQ(table.Size, 0);
    EXPECT_TRUE(lifecycle(&table, 0, 1));
}

TEST(AggregationKernel, OzI64ReducersUseStableDenseSlotsAcrossGrow) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("count.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TCountFn = int64_t(*)(THashTable*, int64_t*, int64_t*, int64_t, int64_t);
    auto count = reinterpret_cast<TCountFn>(entry);
    THashTable table;

    ASSERT_TRUE(count(&table, nullptr, nullptr, 4, 0));
    ASSERT_NE(table.GroupKeys, nullptr);
    ASSERT_NE(table.AggBuffers, nullptr);
    ASSERT_NE(table.AggBuffers[0], nullptr);
    ASSERT_NE(table.AggBuffers[1], nullptr);
    ASSERT_NE(table.AggBuffers[2], nullptr);
    ASSERT_NE(table.AggBuffers[3], nullptr);
    EXPECT_EQ(table.NumAggs, 4);
    EXPECT_EQ(table.Size, 0);
    EXPECT_EQ(count(&table, nullptr, nullptr, 999, 2), -1);

    constexpr std::array<int64_t, 22> input = {
        10, 20, 10, -1, 30, 20, 40, 50, 10, 60,
        70, 80, 90, 100, 110, 120, -1, 50, 120, 120, 130, 140};
    constexpr std::array<int64_t, 22> values = {
        5, 7, -2, 11, 13, 17, 19, 23, 29, 31,
        37, 41, 43, 47, 53, 59, -3, -5, 61, -7,
        std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min()};
    constexpr std::array<int64_t, 15> uniqueKeys = {
        10, 20, -1, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140};
    constexpr std::array<int64_t, 15> expectedCounts = {
        3, 2, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 3, 1, 1};
    constexpr std::array<int64_t, 15> expectedSums = {
        32, 24, 8, 13, 19, 18, 31, 37, 41, 43, 47, 53, 113,
        std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min()};
    constexpr std::array<int64_t, 15> expectedMins = {
        -2, 7, -3, 13, 19, -5, 31, 37, 41, 43, 47, 53, -7,
        std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min()};
    constexpr std::array<int64_t, 15> expectedMaxs = {
        29, 17, 11, 13, 19, 23, 31, 37, 41, 43, 47, 53, 61,
        std::numeric_limits<int64_t>::max(), std::numeric_limits<int64_t>::min()};

    ASSERT_TRUE(count(&table, const_cast<int64_t*>(input.data()),
                      const_cast<int64_t*>(values.data()), input.size(), 1));

    EXPECT_EQ(table.Capacity, 32);
    ASSERT_EQ(table.Size, static_cast<int64_t>(uniqueKeys.size()));
    for (size_t i = 0; i < uniqueKeys.size(); ++i) {
        EXPECT_EQ(table.GroupKeys[i], uniqueKeys[i]);
        EXPECT_EQ(table.AggBuffers[0][i], expectedCounts[i]);
        EXPECT_EQ(table.AggBuffers[1][i], expectedSums[i]);
        EXPECT_EQ(table.AggBuffers[2][i], expectedMins[i]);
        EXPECT_EQ(table.AggBuffers[3][i], expectedMaxs[i]);
        EXPECT_EQ(count(&table, nullptr, nullptr, uniqueKeys[i], 2), expectedCounts[i]);
        EXPECT_EQ(count(&table, nullptr, nullptr, uniqueKeys[i], 3), expectedSums[i]);
        EXPECT_EQ(count(&table, nullptr, nullptr, uniqueKeys[i], 4), expectedMins[i]);
        EXPECT_EQ(count(&table, nullptr, nullptr, uniqueKeys[i], 5), expectedMaxs[i]);
    }

    EXPECT_TRUE(count(&table, nullptr, nullptr, 0, 6));
    EXPECT_EQ(table.Keys, nullptr);
    EXPECT_EQ(table.GroupKeys, nullptr);
    EXPECT_EQ(table.AggBuffers, nullptr);
    EXPECT_EQ(table.Capacity, 0);
    EXPECT_EQ(table.Size, 0);
}

TEST(AggregationKernel, OzBatchAggregationHandlesEmptySingleGroupAndUniqueInputs) {
    void* entry = nullptr;
    std::string error;
    auto runner = CompileKernel("count.oz", entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TBatchFn = int64_t(*)(THashTable*, int64_t*, int64_t*, int64_t, int64_t);
    auto aggregate = reinterpret_cast<TBatchFn>(entry);

    {
        THashTable table;
        ASSERT_TRUE(aggregate(&table, nullptr, nullptr, 4, 0));
        EXPECT_TRUE(aggregate(&table, nullptr, nullptr, 0, 1));
        EXPECT_EQ(table.Size, 0);
        EXPECT_FALSE(aggregate(&table, nullptr, nullptr, -1, 1));
        EXPECT_EQ(table.Size, 0);
        EXPECT_TRUE(aggregate(&table, nullptr, nullptr, 0, 6));
    }

    {
        THashTable table;
        std::array<int64_t, 4> keys = {7, 7, 7, 7};
        std::array<int64_t, 4> values = {5, -2, 11, 3};
        ASSERT_TRUE(aggregate(&table, nullptr, nullptr, 4, 0));
        ASSERT_TRUE(aggregate(&table, keys.data(), values.data(), keys.size(), 1));
        ASSERT_EQ(table.Size, 1);
        EXPECT_EQ(table.GroupKeys[0], 7);
        EXPECT_EQ(table.AggBuffers[0][0], 4);
        EXPECT_EQ(table.AggBuffers[1][0], 17);
        EXPECT_EQ(table.AggBuffers[2][0], -2);
        EXPECT_EQ(table.AggBuffers[3][0], 11);
        EXPECT_TRUE(aggregate(&table, nullptr, nullptr, 0, 6));
    }

    {
        THashTable table;
        std::array<int64_t, 8> keys = {3, 5, 7, 9, 11, 13, 15, 17};
        std::array<int64_t, 8> values = {30, 50, 70, 90, 110, 130, 150, 170};
        ASSERT_TRUE(aggregate(&table, nullptr, nullptr, 4, 0));
        ASSERT_TRUE(aggregate(&table, keys.data(), values.data(), keys.size(), 1));
        EXPECT_EQ(table.Size, 8);
        EXPECT_EQ(table.Capacity, 16);
        for (size_t i = 0; i < keys.size(); ++i) {
            EXPECT_EQ(table.GroupKeys[i], keys[i]);
            EXPECT_EQ(table.AggBuffers[0][i], 1);
            EXPECT_EQ(table.AggBuffers[1][i], values[i]);
            EXPECT_EQ(table.AggBuffers[2][i], values[i]);
            EXPECT_EQ(table.AggBuffers[3][i], values[i]);
        }
        EXPECT_TRUE(aggregate(&table, nullptr, nullptr, 0, 6));
    }
}

TEST(AggregationKernel, OzFinalizeCopiesDenseKeysAndAggregateBuffers) {
    void* aggregateEntry = nullptr;
    void* finalizeEntry = nullptr;
    std::string error;
    auto aggregateRunner = CompileKernel("count.oz", aggregateEntry, error);
    ASSERT_NE(aggregateEntry, nullptr) << error;
    auto finalizeRunner = CompileKernel("finalize.oz", finalizeEntry, error);
    ASSERT_NE(finalizeEntry, nullptr) << error;

    using TBatchFn = int64_t(*)(THashTable*, int64_t*, int64_t*, int64_t, int64_t);
    using TFinalizeFn = int64_t(*)(
        THashTable*, int64_t*, int64_t*, int64_t*, int64_t*, int64_t*, int64_t);
    auto aggregate = reinterpret_cast<TBatchFn>(aggregateEntry);
    auto finalize = reinterpret_cast<TFinalizeFn>(finalizeEntry);

    THashTable table;
    std::array<int64_t, 6> keys = {4, 2, 4, 8, 2, 4};
    std::array<int64_t, 6> values = {10, 7, -3, 11, 5, 20};
    ASSERT_TRUE(aggregate(&table, nullptr, nullptr, 4, 0));
    ASSERT_TRUE(aggregate(&table, keys.data(), values.data(), keys.size(), 1));
    ASSERT_EQ(table.Size, 3);

    std::array<int64_t, 3> outputKeys = {-1, -1, -1};
    std::array<int64_t, 3> outputCounts = {-1, -1, -1};
    std::array<int64_t, 3> outputSums = {-1, -1, -1};
    std::array<int64_t, 3> outputMins = {-1, -1, -1};
    std::array<int64_t, 3> outputMaxs = {-1, -1, -1};

    EXPECT_EQ(finalize(&table, outputKeys.data(), outputCounts.data(),
                       outputSums.data(), outputMins.data(), outputMaxs.data(), 2), -1);
    EXPECT_EQ(outputKeys[0], -1);
    ASSERT_EQ(finalize(&table, outputKeys.data(), outputCounts.data(),
                       outputSums.data(), outputMins.data(), outputMaxs.data(), 3), 3);
    EXPECT_EQ(outputKeys, (std::array<int64_t, 3>{4, 2, 8}));
    EXPECT_EQ(outputCounts, (std::array<int64_t, 3>{3, 2, 1}));
    EXPECT_EQ(outputSums, (std::array<int64_t, 3>{27, 12, 11}));
    EXPECT_EQ(outputMins, (std::array<int64_t, 3>{-3, 5, 11}));
    EXPECT_EQ(outputMaxs, (std::array<int64_t, 3>{20, 7, 11}));

    EXPECT_TRUE(aggregate(&table, nullptr, nullptr, 0, 6));
}

TEST(AggregationKernel, OzStressAggregationHandlesLargeDeterministicInput) {
    void* countEntry = nullptr;
    void* finalizeEntry = nullptr;
    void* checkEntry = nullptr;
    std::string error;
    auto countRunner = CompileKernel("count.oz", countEntry, error);
    ASSERT_NE(countEntry, nullptr) << error;
    auto finalizeRunner = CompileKernel("finalize.oz", finalizeEntry, error);
    ASSERT_NE(finalizeEntry, nullptr) << error;
    auto checkRunner = CompileKernel("check_invariants.oz", checkEntry, error);
    ASSERT_NE(checkEntry, nullptr) << error;

    using TBatchFn = int64_t(*)(THashTable*, int64_t*, int64_t*, int64_t, int64_t);
    using TFinalizeFn = int64_t(*)(
        THashTable*, int64_t*, int64_t*, int64_t*, int64_t*, int64_t*, int64_t);
    using TCheckFn = bool(*)(int64_t*, int64_t*, int64_t);
    auto aggregate = reinterpret_cast<TBatchFn>(countEntry);
    auto finalize = reinterpret_cast<TFinalizeFn>(finalizeEntry);
    auto check = reinterpret_cast<TCheckFn>(checkEntry);

    struct TGroupStats {
        int64_t Count = 0;
        int64_t Sum = 0;
        int64_t Min = 0;
        int64_t Max = 0;
    };

    constexpr size_t rowCount = 2000;
    std::vector<int64_t> keys(rowCount);
    std::vector<int64_t> values(rowCount);
    std::unordered_map<int64_t, TGroupStats> reference;

    uint64_t state = 88172645463325252ULL;
    auto next = [&state]() -> uint64_t {
        state = state * 6364136223846793005ULL + 1442695040888963407ULL;
        return state;
    };
    for (size_t i = 0; i < rowCount; ++i) {
        const int64_t key = static_cast<int64_t>(next() % 301) - 150;
        const int64_t value = static_cast<int64_t>(next() % 2001) - 1000;
        keys[i] = key;
        values[i] = value;
        auto& group = reference[key];
        if (group.Count == 0) {
            group.Min = value;
            group.Max = value;
        } else {
            group.Min = std::min(group.Min, value);
            group.Max = std::max(group.Max, value);
        }
        group.Count += 1;
        group.Sum += value;
    }

    THashTable table;
    ASSERT_TRUE(aggregate(&table, nullptr, nullptr, 4, 0));

    constexpr size_t batchCount = 3;
    size_t offset = 0;
    for (size_t batch = 0; batch < batchCount; ++batch) {
        const size_t remaining = rowCount - offset;
        const size_t batchSize =
            (batch + 1 == batchCount) ? remaining : remaining / (batchCount - batch);
        ASSERT_TRUE(aggregate(&table, keys.data() + offset, values.data() + offset,
                              static_cast<int64_t>(batchSize), 1));
        offset += batchSize;
    }
    ASSERT_EQ(offset, rowCount);

    auto dumpTable = [&table]() {
        std::ostringstream out;
        out << "Capacity=" << table.Capacity << " Size=" << table.Size << "\n";
        for (int64_t slot = 0; slot < table.Capacity; ++slot) {
            if (table.Dist[slot] != -1) {
                out << "  slot " << slot << ": key=" << table.Keys[slot]
                    << " dist=" << table.Dist[slot]
                    << " slotId=" << table.SlotId[slot] << "\n";
            }
        }
        return out.str();
    };

    ASSERT_EQ(table.Size, static_cast<int64_t>(reference.size())) << dumpTable();
    ASSERT_GE(table.Capacity, 256) << dumpTable();
    ASSERT_TRUE(check(table.Keys, table.Dist, table.Capacity)) << dumpTable();

    std::vector<bool> seenSlotId(table.Size, false);
    for (int64_t slot = 0; slot < table.Capacity; ++slot) {
        if (table.Dist[slot] != -1) {
            const int64_t slotId = table.SlotId[slot];
            ASSERT_GE(slotId, 0) << dumpTable();
            ASSERT_LT(slotId, table.Size) << dumpTable();
            ASSERT_FALSE(seenSlotId[slotId]) << "duplicate dense slot id " << slotId << "\n"
                                              << dumpTable();
            seenSlotId[slotId] = true;
        }
    }
    for (bool present : seenSlotId) {
        ASSERT_TRUE(present) << dumpTable();
    }

    std::vector<int64_t> outputKeys(table.Size);
    std::vector<int64_t> outputCounts(table.Size);
    std::vector<int64_t> outputSums(table.Size);
    std::vector<int64_t> outputMins(table.Size);
    std::vector<int64_t> outputMaxs(table.Size);
    ASSERT_EQ(finalize(&table, outputKeys.data(), outputCounts.data(), outputSums.data(),
                       outputMins.data(), outputMaxs.data(), table.Size),
              table.Size);

    for (int64_t i = 0; i < table.Size; ++i) {
        const int64_t key = outputKeys[i];
        auto it = reference.find(key);
        ASSERT_NE(it, reference.end()) << "unexpected key " << key << "\n" << dumpTable();
        const auto& group = it->second;
        EXPECT_EQ(outputCounts[i], group.Count) << "key " << key << "\n" << dumpTable();
        EXPECT_EQ(outputSums[i], group.Sum) << "key " << key << "\n" << dumpTable();
        EXPECT_EQ(outputMins[i], group.Min) << "key " << key << "\n" << dumpTable();
        EXPECT_EQ(outputMaxs[i], group.Max) << "key " << key << "\n" << dumpTable();
        reference.erase(it);
    }
    EXPECT_TRUE(reference.empty()) << "missing " << reference.size() << " keys\n" << dumpTable();

    EXPECT_TRUE(aggregate(&table, nullptr, nullptr, 0, 6));
}

TEST(AggregationKernel, OzMergedLibraryCompilesGeneratedEntryPoint) {
    using namespace NQumir;

    auto library = NQqb::NKernel::ParseFunctionLibrary(
        ReadKernel("count.oz"), {"aggregate_batch", "aggregation_count"});
    ASSERT_TRUE(library) << library.error().ToString();

    // Trivial generated entry, mirroring aggregation_table_lifecycle's
    // op-dispatch shape but calling count_init/count_destroy from the merged
    // library to confirm the merge mechanism without TRowSet/HashTable
    // aggregation semantics.
    constexpr const char* entrySource = R"(
(block
  (fun lib_smoke ((var ht <ref HashTable>) (var capacity i64) (var op i64)) -> i64
    (block
      (return
        (if (== op (: 0 i64))
          (cast (call count_init ht capacity) i64)
          (block
            (call count_destroy ht)
            (: 1 i64)))))))
)";
    auto entryFun = NQqb::NKernel::ParseFunctionLibrary(entrySource);
    ASSERT_TRUE(entryFun) << entryFun.error().ToString();
    ASSERT_EQ(entryFun->size(), 1u);

    auto merged = NQqb::NKernel::MergeKernelLibrary(*library, entryFun->front());

    TLLVMRunnerOptions options;
    options.CoreInput = true;
    options.NativeCode = true;
    options.AllowOverloads = true;

    TLLVMRunner runner(options);
    runner.RegisterModule(std::make_shared<NRegistry::QumirDbModule>(), true);

    std::string error;
    void* entry = runner.CompileKernelAst(merged, &error);
    ASSERT_NE(entry, nullptr) << error;

    using TLibSmokeFn = int64_t(*)(THashTable*, int64_t, int64_t);
    auto smoke = reinterpret_cast<TLibSmokeFn>(entry);

    THashTable table;
    ASSERT_TRUE(smoke(&table, 8, 0));
    ASSERT_NE(table.Keys, nullptr);
    ASSERT_NE(table.Dist, nullptr);
    ASSERT_NE(table.SlotId, nullptr);
    ASSERT_NE(table.GroupKeys, nullptr);
    ASSERT_NE(table.AggBuffers, nullptr);
    EXPECT_EQ(table.Capacity, 8);
    EXPECT_EQ(table.Size, 0);
    EXPECT_EQ(table.NumAggs, 4);
    EXPECT_EQ(table.NumKeys, 1);

    EXPECT_TRUE(smoke(&table, 0, 1));
    EXPECT_EQ(table.Keys, nullptr);
    EXPECT_EQ(table.AggBuffers, nullptr);
    EXPECT_EQ(table.Capacity, 0);
    EXPECT_EQ(table.Size, 0);
    EXPECT_EQ(table.NumAggs, 0);
}

TEST(AggregationKernel, OzAggregateDispatchUpdatesHashTableFromRowSet) {
    std::unordered_map<std::string, int32_t> fieldIndices = {{"k", 0}, {"v", 1}};
    void* entry = nullptr;
    std::string error;
    auto runner = CompileAggregateDispatch(fieldIndices, "k", std::string("v"), entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TDispatchFn = int64_t(*)(THashTable*, NQqb::TRowSet*, int64_t, int64_t);
    auto dispatch = reinterpret_cast<TDispatchFn>(entry);

    THashTable table;
    ASSERT_TRUE(dispatch(&table, nullptr, 4, 0));

    struct TGroupStats {
        int64_t Count = 0;
        int64_t Sum = 0;
        int64_t Min = 0;
        int64_t Max = 0;
    };
    std::unordered_map<int64_t, TGroupStats> reference;
    auto accumulate = [&](int64_t key, int64_t value) {
        auto& group = reference[key];
        if (group.Count == 0) {
            group.Min = value;
            group.Max = value;
        } else {
            group.Min = std::min(group.Min, value);
            group.Max = std::max(group.Max, value);
        }
        group.Count += 1;
        group.Sum += value;
    };

    // Batch 1: 4 rows, the last one is filtered out by Selection.
    {
        std::vector<int64_t> keys = {1, 2, 1, 3};
        std::vector<int64_t> vals = {10, 20, 5, 7};
        std::vector<uint8_t> selection = {1, 1, 1, 0};
        NQqb::TColumn cols[2] = {};
        cols[0].Data = reinterpret_cast<char*>(keys.data());
        cols[1].Data = reinterpret_cast<char*>(vals.data());
        NQqb::TRowSet rowSet{};
        rowSet.Columns = cols;
        rowSet.ColumnCount = 2;
        rowSet.RowCount = static_cast<int64_t>(keys.size());
        rowSet.Selection = selection.data();

        EXPECT_EQ(dispatch(&table, &rowSet, 0, 1), 0);
        for (size_t i = 0; i < keys.size(); ++i) {
            if (selection[i]) {
                accumulate(keys[i], vals[i]);
            }
        }
    }

    // Batch 2: no Selection (every row processed).
    {
        std::vector<int64_t> keys = {2, 4};
        std::vector<int64_t> vals = {3, 100};
        NQqb::TColumn cols[2] = {};
        cols[0].Data = reinterpret_cast<char*>(keys.data());
        cols[1].Data = reinterpret_cast<char*>(vals.data());
        NQqb::TRowSet rowSet{};
        rowSet.Columns = cols;
        rowSet.ColumnCount = 2;
        rowSet.RowCount = static_cast<int64_t>(keys.size());
        rowSet.Selection = nullptr;

        EXPECT_EQ(dispatch(&table, &rowSet, 0, 1), 0);
        for (size_t i = 0; i < keys.size(); ++i) {
            accumulate(keys[i], vals[i]);
        }
    }

    ASSERT_EQ(table.Size, static_cast<int64_t>(reference.size()));
    for (int64_t slot = 0; slot < table.Capacity; ++slot) {
        if (table.Dist[slot] == -1) continue;
        const int64_t key = table.Keys[slot];
        const int64_t denseSlot = table.SlotId[slot];
        auto it = reference.find(key);
        ASSERT_NE(it, reference.end()) << "unexpected key " << key;
        const auto& group = it->second;
        EXPECT_EQ(table.AggBuffers[0][denseSlot], group.Count) << "key " << key;
        EXPECT_EQ(table.AggBuffers[1][denseSlot], group.Sum) << "key " << key;
        EXPECT_EQ(table.AggBuffers[2][denseSlot], group.Min) << "key " << key;
        EXPECT_EQ(table.AggBuffers[3][denseSlot], group.Max) << "key " << key;
    }

    EXPECT_TRUE(dispatch(&table, nullptr, 0, 6));
}

TEST(AggregationKernel, OzAggregateDispatchCountStarWithoutArgColumn) {
    std::unordered_map<std::string, int32_t> fieldIndices = {{"k", 0}};
    void* entry = nullptr;
    std::string error;
    auto runner = CompileAggregateDispatch(fieldIndices, "k", std::nullopt, entry, error);
    ASSERT_NE(entry, nullptr) << error;

    using TDispatchFn = int64_t(*)(THashTable*, NQqb::TRowSet*, int64_t, int64_t);
    auto dispatch = reinterpret_cast<TDispatchFn>(entry);

    THashTable table;
    ASSERT_TRUE(dispatch(&table, nullptr, 4, 0));

    std::vector<int64_t> keys = {1, 1, 2, 1, 2, 3};
    NQqb::TColumn cols[1] = {};
    cols[0].Data = reinterpret_cast<char*>(keys.data());
    NQqb::TRowSet rowSet{};
    rowSet.Columns = cols;
    rowSet.ColumnCount = 1;
    rowSet.RowCount = static_cast<int64_t>(keys.size());
    rowSet.Selection = nullptr;

    EXPECT_EQ(dispatch(&table, &rowSet, 0, 1), 0);

    std::unordered_map<int64_t, int64_t> counts;
    for (int64_t key : keys) {
        counts[key] += 1;
    }

    ASSERT_EQ(table.Size, static_cast<int64_t>(counts.size()));
    for (int64_t slot = 0; slot < table.Capacity; ++slot) {
        if (table.Dist[slot] == -1) continue;
        const int64_t key = table.Keys[slot];
        const int64_t denseSlot = table.SlotId[slot];
        auto it = counts.find(key);
        ASSERT_NE(it, counts.end()) << "unexpected key " << key;
        EXPECT_EQ(table.AggBuffers[0][denseSlot], it->second) << "count, key " << key;
        // No arg column: agg_dispatch passes a constant 0 as the value, so
        // sum/min/max collapse to 0 for every group.
        EXPECT_EQ(table.AggBuffers[1][denseSlot], 0) << "sum, key " << key;
        EXPECT_EQ(table.AggBuffers[2][denseSlot], 0) << "min, key " << key;
        EXPECT_EQ(table.AggBuffers[3][denseSlot], 0) << "max, key " << key;
    }

    EXPECT_TRUE(dispatch(&table, nullptr, 0, 6));
}

TEST(AggregationKernel, OzGeneratedReducersAreCalledByStaticName) {
    using TSmokeFn = void(*)(int64_t, int64_t, int64_t, int64_t*);

    // N=4, same order as count.oz's agg_count_step/agg_sum_i64_step/
    // agg_min_i64_step/agg_max_i64_step.
    {
        void* entry = nullptr;
        std::string error;
        auto runner = CompileReducerSmoke({"count", "sum", "min", "max"}, entry, error);
        ASSERT_NE(entry, nullptr) << error;
        auto smoke = reinterpret_cast<TSmokeFn>(entry);

        std::array<int64_t, 4> out{};
        smoke(/*prev=*/0, /*value=*/10, /*is_new=*/1, out.data());
        EXPECT_EQ(out[0], 1);   // count: first value -> count = 1
        EXPECT_EQ(out[1], 10);  // sum: prev + value
        EXPECT_EQ(out[2], 10);  // min: is_new -> value
        EXPECT_EQ(out[3], 10);  // max: is_new -> value

        smoke(/*prev=*/5, /*value=*/3, /*is_new=*/0, out.data());
        EXPECT_EQ(out[0], 6);   // count: prev + 1
        EXPECT_EQ(out[1], 8);   // sum: prev + value
        EXPECT_EQ(out[2], 3);   // min: value < prev -> value
        EXPECT_EQ(out[3], 5);   // max: value < prev -> prev

        smoke(/*prev=*/5, /*value=*/9, /*is_new=*/0, out.data());
        EXPECT_EQ(out[2], 5);   // min: value > prev -> prev
        EXPECT_EQ(out[3], 9);   // max: value > prev -> value
    }

    // N=2, non-default order/composition (max then count): proves the set
    // and order of generated reducers is exactly `funcs`, not a fixed 4.
    {
        void* entry = nullptr;
        std::string error;
        auto runner = CompileReducerSmoke({"max", "count"}, entry, error);
        ASSERT_NE(entry, nullptr) << error;
        auto smoke = reinterpret_cast<TSmokeFn>(entry);

        std::array<int64_t, 2> out{};
        smoke(/*prev=*/0, /*value=*/-7, /*is_new=*/1, out.data());
        EXPECT_EQ(out[0], -7); // reduce_0 == max, is_new -> value
        EXPECT_EQ(out[1], 1);  // reduce_1 == count

        smoke(/*prev=*/-7, /*value=*/-3, /*is_new=*/0, out.data());
        EXPECT_EQ(out[0], -3); // max(-7, -3) == -3
        EXPECT_EQ(out[1], -6); // count: prev + 1
    }

    // N=1.
    {
        void* entry = nullptr;
        std::string error;
        auto runner = CompileReducerSmoke({"sum"}, entry, error);
        ASSERT_NE(entry, nullptr) << error;
        auto smoke = reinterpret_cast<TSmokeFn>(entry);

        std::array<int64_t, 1> out{};
        smoke(/*prev=*/100, /*value=*/23, /*is_new=*/0, out.data());
        EXPECT_EQ(out[0], 123); // sum: prev + value
    }
}

TEST(AggregationKernel, OzApplyReducersUpdatesAllBuffersByStaticName) {
    using TApplyFn = void(*)(int64_t**, int64_t, int64_t, int64_t);

    // N=4, same order as count.oz's agg_count_step/agg_sum_i64_step/
    // agg_min_i64_step/agg_max_i64_step.
    {
        void* entry = nullptr;
        std::string error;
        auto runner = CompileApplyReducersSmoke({"count", "sum", "min", "max"}, entry, error);
        ASSERT_NE(entry, nullptr) << error;
        auto apply = reinterpret_cast<TApplyFn>(entry);

        std::array<int64_t, 1> counts{0};
        std::array<int64_t, 1> sums{0};
        std::array<int64_t, 1> mins{0};
        std::array<int64_t, 1> maxs{0};
        std::array<int64_t*, 4> buffers{counts.data(), sums.data(), mins.data(), maxs.data()};

        apply(buffers.data(), /*dense_slot=*/0, /*value=*/10, /*is_new=*/1);
        EXPECT_EQ(counts[0], 1);
        EXPECT_EQ(sums[0], 10);
        EXPECT_EQ(mins[0], 10);
        EXPECT_EQ(maxs[0], 10);

        apply(buffers.data(), /*dense_slot=*/0, /*value=*/3, /*is_new=*/0);
        EXPECT_EQ(counts[0], 2);
        EXPECT_EQ(sums[0], 13);
        EXPECT_EQ(mins[0], 3);
        EXPECT_EQ(maxs[0], 10);

        apply(buffers.data(), /*dense_slot=*/0, /*value=*/20, /*is_new=*/0);
        EXPECT_EQ(counts[0], 3);
        EXPECT_EQ(sums[0], 33);
        EXPECT_EQ(mins[0], 3);
        EXPECT_EQ(maxs[0], 20);
    }

    // N=2, non-default order/composition (max then count), at a non-zero
    // dense_slot to confirm indexing into agg_buffers[i][dense_slot].
    {
        void* entry = nullptr;
        std::string error;
        auto runner = CompileApplyReducersSmoke({"max", "count"}, entry, error);
        ASSERT_NE(entry, nullptr) << error;
        auto apply = reinterpret_cast<TApplyFn>(entry);

        std::array<int64_t, 2> maxs{0, 0};
        std::array<int64_t, 2> counts{0, 0};
        std::array<int64_t*, 2> buffers{maxs.data(), counts.data()};

        apply(buffers.data(), /*dense_slot=*/1, /*value=*/-7, /*is_new=*/1);
        EXPECT_EQ(maxs[1], -7);  // reduce_0 == max, is_new -> value
        EXPECT_EQ(counts[1], 1); // reduce_1 == count
        EXPECT_EQ(maxs[0], 0);   // slot 0 untouched
        EXPECT_EQ(counts[0], 0); // slot 0 untouched

        apply(buffers.data(), /*dense_slot=*/1, /*value=*/-3, /*is_new=*/0);
        EXPECT_EQ(maxs[1], -3);  // max(-7, -3) == -3
        EXPECT_EQ(counts[1], 2); // count: prev + 1
    }

    // N=1.
    {
        void* entry = nullptr;
        std::string error;
        auto runner = CompileApplyReducersSmoke({"sum"}, entry, error);
        ASSERT_NE(entry, nullptr) << error;
        auto apply = reinterpret_cast<TApplyFn>(entry);

        std::array<int64_t, 1> sums{100};
        std::array<int64_t*, 1> buffers{sums.data()};

        apply(buffers.data(), /*dense_slot=*/0, /*value=*/23, /*is_new=*/0);
        EXPECT_EQ(sums[0], 123); // sum: prev + value
    }
}

int main(int argc, char** argv) {
    if (argc > 1) {
        KernelDir = argv[1];
    }
    ::testing::InitGoogleTest(&argc, argv);
    NQumir::NCodeGen::TLLVMInitializer llvmInit;
    return RUN_ALL_TESTS();
}
