#pragma once

#include <qdb/kernel/aggregate_key.h>

#include <qumir/parser/ast.h>
#include <qumir/parser/type.h>

#include <cstddef>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>

namespace NQqb {
namespace NKernel {

// Generates concrete overloads consumed by the generic Robin Hood library:
//   rh_hash(Key) -> i64
//   rh_key_equal(Key, Key) -> bool
// Integer/f64 scalar and recursively composed struct representations are
// generated by walking the concrete key type without changing generic Oz code.
std::vector<NQumir::NAst::TExprPtr> GenKeyOperationFunDecls(
    const TAggregateKeyDescriptor& key);

void SubstFieldsInPlace(
    NQumir::NAst::TExprPtr& expr,
    const std::unordered_set<std::string>& fieldNames,
    const NQumir::NAst::TExprPtr& indexIdent);

// Builds a vectorized filter kernel that takes (ref TRowSet) directly.
// fieldIndices maps each field name to its index in TRowSet.Columns.
NQumir::NAst::TExprPtr GenFilterKernelAst(
    NQumir::NAst::TExprPtr predicate,
    const NQumir::NAst::TStructType& inputType,
    const std::unordered_map<std::string, int32_t>& fieldIndices,
    NQumir::NAst::TTypePtr columnType,
    NQumir::NAst::TTypePtr rowSetType);

// Builds the generic aggregation dispatch entry over aht_init/aht_update/
// aht_destroy from aggregation_hashtable_generic.oz. Key extraction is driven
// by the descriptor instead of a hardcoded i64 field. The first connected
// Supports scalar and composite fixed-width integer/f64 keys. Aggregate values
// still use one shared integer input column and i64 reducer states.
NQumir::NAst::TExprPtr GenGenericAggregateDispatchAst(
    const NQumir::NAst::TStructType& inputType,
    const TAggregateKeyDescriptor& key,
    const std::optional<std::string>& argField,
    size_t numAggs,
    NQumir::NAst::TTypePtr columnType,
    NQumir::NAst::TTypePtr rowSetType,
    NQumir::NAst::TTypePtr hashTableType);

// Builds the byte-oriented finalize ABI. C++ supplies one opaque u8 destination
// per logical key field; the generated wrapper casts each destination to its
// concrete pointer type and projects dense AoS Key values into SoA columns.
NQumir::NAst::TExprPtr GenGenericAggregateFinalizeAst(
    const TAggregateKeyDescriptor& key,
    NQumir::NAst::TTypePtr hashTableType);

// Generates N = funcs.size() FunDecls named reduce_0..reduce_{N-1}, each with
// the predefined reducer contract from PLAN_AGGREGATION.md section 4:
//   reduce_i(i64 prev, i64 value, bool is_new) -> i64
// funcs[i] selects the body ("count"|"sum"|"min"|"max"), generated under the
// positional name reduce_i. N is exactly funcs.size(), not a fixed builtin set.
//
// The result is meant for static injection via MergeKernelLibrary before
// kernel compilation: generated table code calls reduce_0..reduce_{N-1}
// directly by name (no function pointers, no runtime dispatch on Func).
std::vector<NQumir::NAst::TExprPtr> GenReducerFunDecls(
    const std::vector<std::string>& funcs);

// Generates a single FunDecl:
//   agg_apply_reducers(<ptr <ptr i64>> agg_buffers, i64 dense_slot,
//                       i64 value, bool is_new)
// which for i in [0, numReducers) does
//   agg_buffers[i][dense_slot] = reduce_i(agg_buffers[i][dense_slot], value, is_new)
// — numReducers static, direct, by-name calls to the reduce_0..reduce_{N-1}
// functions from GenReducerFunDecls.
//
// This is the one piece of per-query generated code that the NumAggs-generic
// table library (agg_init/agg_rehash/agg_update/agg_destroy/agg_finalize,
// L2b) calls by static name to update all N aggregate buffers for one dense
// slot. Everything else in that library is agg-count-agnostic and driven by
// ht.NumAggs/ht.AggBuffers at runtime.
NQumir::NAst::TExprPtr GenApplyReducersFunDecl(size_t numReducers);

} // namespace NKernel
} // namespace NQqb
