#pragma once

#include <qdb/kernel/aggregate_key.h>

#include <qumir/parser/ast.h>
#include <qumir/parser/type.h>

#include <cstddef>
#include <optional>
#include <string>
#include <unordered_map>
#include <unordered_set>

namespace NQqb {
namespace NKernel {

// count.oz's fixed-NumAggs=4 functions and old op-coded entry points
// (count_init/count_rehash/count_update/count_destroy/agg_*_step/
// aggregate_batch/aggregation_count). Excluding these from count.oz keeps
// rh_hash_i64/count_lookup/count_insert_existing (shared) plus the
// NumAggs-generic agg_init/agg_rehash/agg_update/agg_destroy (L2b-2) — the
// library that GenAggregateKernelAst's agg_dispatch (L2c) must be merged
// with.
extern const std::unordered_set<std::string> kCountOzFixedFuncs;

// Generates concrete overloads consumed by the generic Robin Hood library:
//   rh_hash(Key) -> i64
//   rh_key_equal(Key, Key) -> bool
// Integer scalar and integer-struct representations are generated by walking
// the concrete key type. Other leaf types are added without changing the
// generic Oz library.
std::vector<NQumir::NAst::TExprPtr> GenKeyOperationFunDecls(
    const TAggregateKeyDescriptor& key);

void SubstFieldsInPlace(
    NQumir::NAst::TExprPtr& expr,
    const std::unordered_set<std::string>& fieldNames,
    const NQumir::NAst::TExprPtr& indexIdent);

// Builds a vectorized filter kernel that takes (ref TRowSet) directly.
// fieldIndices maps each field name to its index in TRowSet.Columns.
NQumir::NAst::TExprPtr GenFilterKernelAst(
    NQumir::NAst::TExprPtr predicate,
    const NQumir::NAst::TStructType& inputType,
    const std::unordered_map<std::string, int32_t>& fieldIndices,
    NQumir::NAst::TTypePtr columnType,
    NQumir::NAst::TTypePtr rowSetType);

// Builds an op-dispatched aggregation update kernel:
//   agg_dispatch(ref HashTable ht, ref TRowSet batch, i64 arg, i64 op) -> i64
// op == 0: agg_init(ht, arg, numAggs)       (init, capacity = arg)
// op == 1: for each selected row in batch, agg_update(ht, key, value)
//          (value = the argField column, or constant 0 if argField is unset)
// otherwise: agg_destroy(ht)
// keyField and argField (if set) must name i64 columns (Stage 1: integer
// keys/args only); fieldIndices maps their names to TRowSet.Columns indices.
// numAggs is the query's aggregate count, baked into the agg_init call.
// The result calls agg_init/agg_update/agg_destroy (L2b's NumAggs-generic
// table, which itself calls agg_apply_reducers), so it must be merged (see
// MergeKernelLibrary) with count.oz's NumAggs-generic FunDecls and with
// reduce_0..reduce_{numAggs-1}/agg_apply_reducers (GenReducerFunDecls/
// GenApplyReducersFunDecl) before compiling. The reducers and
// agg_apply_reducers must precede agg_update in the merged Stmts order
// (type annotation is a single forward pass — see PLAN_AGGREGATION.md's
// L2b-2 notes).
NQumir::NAst::TExprPtr GenAggregateKernelAst(
    const std::unordered_map<std::string, int32_t>& fieldIndices,
    const std::string& keyField,
    const std::optional<std::string>& argField,
    size_t numAggs,
    NQumir::NAst::TTypePtr columnType,
    NQumir::NAst::TTypePtr rowSetType,
    NQumir::NAst::TTypePtr hashTableType);

// Builds the generic aggregation dispatch entry over aht_init/aht_update/
// aht_destroy from aggregation_hashtable_generic.oz. Key extraction is driven
// by the descriptor instead of a hardcoded i64 field. The first connected
// production slice supports a scalar key and an optional i64 value column;
// composite materialization is added as the next M5 step.
NQumir::NAst::TExprPtr GenGenericAggregateDispatchAst(
    const NQumir::NAst::TStructType& inputType,
    const TAggregateKeyDescriptor& key,
    const std::optional<std::string>& argField,
    size_t numAggs,
    NQumir::NAst::TTypePtr columnType,
    NQumir::NAst::TTypePtr rowSetType,
    NQumir::NAst::TTypePtr hashTableType);

// Builds the current scalar finalize ABI and forwards it to generic
// aht_finalize<Key>. Composite keys will replace the single typed output key
// pointer with generated projection into one output column per key field.
NQumir::NAst::TExprPtr GenGenericAggregateFinalizeAst(
    const TAggregateKeyDescriptor& key,
    NQumir::NAst::TTypePtr hashTableType);

// Generates N = funcs.size() FunDecls named reduce_0..reduce_{N-1}, each with
// the predefined reducer contract from PLAN_AGGREGATION.md section 4:
//   reduce_i(i64 prev, i64 value, bool is_new) -> i64
// funcs[i] selects the body ("count"|"sum"|"min"|"max" — the same bodies as
// count.oz's agg_count_step/agg_sum_i64_step/agg_min_i64_step/agg_max_i64_step),
// generated under the positional name reduce_i. N is exactly funcs.size(),
// not a fixed builtin set.
//
// The result is meant for static injection via MergeKernelLibrary before
// kernel compilation: generated table code calls reduce_0..reduce_{N-1}
// directly by name (no function pointers, no runtime dispatch on Func).
std::vector<NQumir::NAst::TExprPtr> GenReducerFunDecls(
    const std::vector<std::string>& funcs);

// Generates a single FunDecl:
//   agg_apply_reducers(<ptr <ptr i64>> agg_buffers, i64 dense_slot,
//                       i64 value, bool is_new)
// which for i in [0, numReducers) does
//   agg_buffers[i][dense_slot] = reduce_i(agg_buffers[i][dense_slot], value, is_new)
// — numReducers static, direct, by-name calls to the reduce_0..reduce_{N-1}
// functions from GenReducerFunDecls.
//
// This is the one piece of per-query generated code that the NumAggs-generic
// table library (agg_init/agg_rehash/agg_update/agg_destroy/agg_finalize,
// L2b) calls by static name to update all N aggregate buffers for one dense
// slot. Everything else in that library is agg-count-agnostic and driven by
// ht.NumAggs/ht.AggBuffers at runtime.
NQumir::NAst::TExprPtr GenApplyReducersFunDecl(size_t numReducers);

} // namespace NKernel
} // namespace NQqb
